linters:
  enable:
    ##### Recommended from reddit
    - wrapcheck
    - revive
    - nilerr
    - gosec
    - gochecksumtype
    - exhaustive
    ##### defaults
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
