name: gorant

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    restart: unless-stopped
    environment:
      LISTEN_ADDR: ${LISTEN_ADDR}
